create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  storage_path text not null unique,
  filename text not null,
  title text not null default 'Untitled',
  category text not null default 'Unsorted',
  labels text not null default '',
  notes text not null default '',
  content_type text not null,
  size bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists photos_category_idx on public.photos (category);
create index if not exists photos_created_idx on public.photos (created_at desc);

create table if not exists public.topics (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists topics_sort_idx on public.topics (sort_order, name);

create table if not exists public.studio_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('photos', 'photos', true)
on conflict (id) do update set public = true;

alter table public.photos enable row level security;
alter table public.topics enable row level security;
alter table public.studio_settings enable row level security;

drop policy if exists "Public can read published portfolio metadata" on public.photos;
create policy "Public can read published portfolio metadata"
on public.photos for select
using (true);

drop policy if exists "Public can read topics" on public.topics;
create policy "Public can read topics"
on public.topics for select
using (true);

drop policy if exists "Public can read portfolio photos" on storage.objects;
create policy "Public can read portfolio photos"
on storage.objects for select
using (bucket_id = 'photos');
